"""baseline schema

Revision ID: f06b1082daff
Revises: 
Create Date: 2026-10-01 15:02:26.066427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f06b1082daff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.drop_index(op.f('idx_foods_availability'), table_name='foods')
    op.drop_index(op.f('idx_foods_category'), table_name='foods')
    op.create_index(op.f('ix_foods_id'), 'foods', ['id'], unique=False)
    op.drop_index(op.f('idx_order_items_food'), table_name='order_items')
    op.drop_index(op.f('idx_order_items_order'), table_name='order_items')
    op.create_index(op.f('ix_order_items_food_id'), 'order_items', ['food_id'], unique=False)
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.alter_column('orders', 'status',
               existing_type=mysql.ENUM('Pending', 'Confirmed', 'Preparing', 'Out for Delivery', 'Delivered', 'Cancelled'),
               type_=sa.Enum('pending', 'confirmed', 'preparing', 'out_for_delivery', 'delivered', 'cancelled', name='orderstatusenum'),
               existing_nullable=True,
               existing_server_default=sa.text("'Pending'"))
    op.drop_index(op.f('idx_orders_customer'), table_name='orders')
    op.drop_index(op.f('idx_orders_status'), table_name='orders')
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.drop_index(op.f('email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.create_index(op.f('idx_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('idx_orders_customer'), 'orders', ['customer_id'], unique=False)
    op.alter_column('orders', 'status',
               existing_type=sa.Enum('pending', 'confirmed', 'preparing', 'out_for_delivery', 'delivered', 'cancelled', name='orderstatusenum'),
               type_=mysql.ENUM('Pending', 'Confirmed', 'Preparing', 'Out for Delivery', 'Delivered', 'Cancelled'),
               existing_nullable=True,
               existing_server_default=sa.text("'Pending'"))
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_food_id'), table_name='order_items')
    op.create_index(op.f('idx_order_items_order'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('idx_order_items_food'), 'order_items', ['food_id'], unique=False)
    op.drop_index(op.f('ix_foods_id'), table_name='foods')
    op.create_index(op.f('idx_foods_category'), 'foods', ['category_id'], unique=False)
    op.create_index(op.f('idx_foods_availability'), 'foods', ['is_available'], unique=False)
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    # ### end Alembic commands ###
