import { useState, useEffect } from "react";
import { Link } from "react-router-dom";
import { getFoods } from "../api/foods";
import { getCategories } from "../api/categories";
import placeholder from "../assets/food-placeholder.svg";
import FoodCard from "../components/FoodCard";
export default function Home() {
 const [foods, setFoods] = useState([]), [categories, setCategories] = useState([]), [loading, setLoading] = useState(true), [error, setError] = useState(false), [attempt, setAttempt] = useState(0);
 useEffect(() => { let active = true; Promise.all([getFoods({limit: 3, is_available: true}), getCategories()]).then(([f,c]) => { if(active){setFoods(f.data.items);setCategories(c.data);} }).catch(() => {if(active)setError(true);}).finally(() => {if(active)setLoading(false);}); return () => {active=false;}; }, [attempt]);
 return <><section className="hero page-width"><div className="hero-copy"><p className="eyebrow">A taste of happiness</p><h1>Good food.<br />Great <em>mood.</em></h1><p className="hero-description">From comforting classics to your next favorite. Find a little joy in every bite.</p><Link className="primary-button" to="/menu">Explore menu <span>&#8599;</span></Link><div className="hero-footnote"><span className="little-star">&#10035;</span> Sri Lankan flavors. Something for everyone.</div></div><div className="hero-visual"><img src="https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=90" alt="An appetizing spread of colorful bowls with fresh vegetables and hearty ingredients" fetchPriority="high" onError={e => { e.currentTarget.onerror = null; e.currentTarget.src = placeholder; e.currentTarget.alt = "A plated meal illustration"; }} /><div className="hero-stamp">GOOD FOOD<br /><span>good days</span> EVERY DAY</div><div className="hero-caption"><span>On the menu today</span><strong>Your next favorite meal.</strong></div></div></section><div className="brand-strip"><span>Big flavors</span><span aria-hidden="true">&#10035;</span><span>Everyday favorites</span><span aria-hidden="true">&#10035;</span><span>Made for good moods</span></div><section className="page-width discovery"><div className="section-heading"><div><p className="eyebrow">Follow your cravings</p><h2>What sounds good?</h2></div><Link to="/menu">View the full menu &#8599;</Link></div><div className="category-links"><Link to="/menu">All dishes <span>&#8599;</span></Link>{categories.map(c => <Link key={c.id} to={`/menu?category_id=${c.id}`}>{c.name}<span>&#8599;</span></Link>)}</div><div className="section-heading popular-heading"><div><p className="eyebrow">Find your new favorite</p><h2>Popular picks</h2></div><p>A good place to start.</p></div>{loading ? <div role="status" className="food-grid">{[0,1,2].map(i=><div key={i} className="food-skeleton" />)}<span className="sr-only">Loading menu</span></div> : error ? <div className="empty-panel" role="alert"><h3>The menu is taking a moment.</h3><p>We couldn't load the dishes. Please try again.</p><button className="primary-button" onClick={()=>{setError(false);setLoading(true);setAttempt(a=>a+1);}}>Try again</button></div> : foods.length ? <div className="food-grid">{foods.map(f=><FoodCard key={f.id} food={f}/>)}</div> : <div className="empty-panel">Fresh picks will appear here when the menu is available.</div>}</section><section className="invitation page-width"><span className="little-star">&#10035;</span><h2>Make room for<br /><em>something delicious.</em></h2><Link className="primary-button" to="/menu">Find your favorite &#8599;</Link></section></>;
}
