import { useEffect, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { getFoods } from "../api/foods";
import { getCategories } from "../api/categories";
import FoodCard from "../components/FoodCard";
export default function Menu() {
 const [params, setParams] = useSearchParams();
 const [foods,setFoods]=useState([]), [categories,setCategories]=useState([]), [loading,setLoading]=useState(true), [error,setError]=useState(''), [pagination,setPagination]=useState({total_pages:1,total:0}), [attempt,setAttempt]=useState(0);
 const search=params.get('search')||'', category=params.get('category_id')||'', sort=params.get('sort')||'', order=params.get('order')||'asc', page=Number(params.get('page'))||1;
 const update=(values)=>setParams(previous=>{const next=new URLSearchParams(previous);Object.entries({...values,page:values.page||1}).forEach(([k,v])=>v?next.set(k,String(v)):next.delete(k));return next;});
 useEffect(()=>{let active=true;getCategories().then(r=>{if(active)setCategories(r.data);}).catch(()=>{if(active)setError('Category filters could not load. You can still search the menu.');});return()=>{active=false;};},[attempt]);
 useEffect(()=>{let active=true;getFoods({search,category_id:category,sort,order,page,limit:9}).then(r=>{if(active){setFoods(r.data.items);setPagination(r.data);}}).catch(()=>{if(active){setFoods([]);setError('We could not load the menu. Please try again.');}}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[search,category,sort,order,page,attempt]);
 const change=(v)=>{if(Object.entries(v).every(([k,value]) => String(value) === (params.get(k) || (k === 'page' ? '1' : '')))) return; setLoading(true);setError('');update(v);};
 return <div className="page-width menu-page"><header className="page-heading"><p className="eyebrow">Something for every craving</p><h1>The good mood menu.</h1><p>Find your favorites. Discover something delicious.</p></header><div className="menu-tools"><label className="search-field"><span aria-hidden="true">&#8981;</span><span className="sr-only">Search food</span><input placeholder="What are you craving?" value={search} onChange={e=>change({search:e.target.value})}/></label><label><span className="sr-only">Sort dishes</span><select value={sort} onChange={e=>change({sort:e.target.value})}><option value="">Sort by</option><option value="price">Price</option><option value="name">Name</option></select></label><label><span className="sr-only">Sort direction</span><select value={order} onChange={e=>change({order:e.target.value})}><option value="asc">Low to high / A–Z</option><option value="desc">High to low / Z–A</option></select></label></div><div className="filter-chips" aria-label="Food categories">{[{id:'',name:'All dishes'},...categories].map(c=><button key={c.id} aria-pressed={category===String(c.id)} className={category===String(c.id)?'active':''} onClick={()=>change({category_id:c.id})}>{c.name}</button>)}</div>{error && <div role="alert" className="empty-panel"><p>{error}</p><button className="primary-button" onClick={()=>{setLoading(true);setError('');setAttempt(a=>a+1);}}>Try again</button></div>}{loading ? <div role="status" className="food-grid">{[0,1,2,3,4,5].map(i=><div key={i} className="food-skeleton"/>)}<span className="sr-only">Loading dishes</span></div> : !error && <><p className="results-count" aria-live="polite">{pagination.total ?? foods.length} dishes to explore</p><div className="food-grid">{foods.map(f=><FoodCard key={f.id} food={f}/>)}</div>{foods.length===0 && <div className="empty-panel"><h2>No dishes found</h2><p>Try another craving or clear your filters.</p><button className="primary-button" onClick={()=>{if(params.size) {setLoading(true);setParams({});}}}>Clear filters</button></div>}</>}{!loading && !error && pagination.total_pages>1 && <nav className="pagination" aria-label="Menu pages"><button disabled={page<=1} onClick={()=>change({page:page-1})}>&#8592; Previous</button><span>Page {page} of {pagination.total_pages}</span><button disabled={page>=pagination.total_pages} onClick={()=>change({page:page+1})}>Next &#8594;</button></nav>}</div>;
}
